/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gasandco.com;

import java.awt.HeadlessException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FuelChargeForm extends javax.swing.JFrame {

    private ArrayList<FuelPump> fuelPumps;
    private ArrayList<Customer> customers;
    private ArrayList<FuelCharge> fuelCharges;
    private ArrayList<DiscountStrategy> discountStrategies;
    private ArrayList<FuelType> fuelTypes;
    private PumpDisplay pumpDisplay;
    private Validator validator;

    public ArrayList<FuelCharge> getFuelCharges() {
        return fuelCharges;
    }

    public void setFuelCharges(ArrayList<FuelCharge> fuelCharges) {
        this.fuelCharges = fuelCharges;
    }

    public ArrayList<FuelType> getFuelTypes() {
        return fuelTypes;
    }

    public void setFuelTypes(ArrayList<FuelType> fuelTypes) {
        this.fuelTypes = fuelTypes;
    }

    public FuelChargeForm(ArrayList<FuelPump> fuelPumps, ArrayList<Customer> customers, ArrayList<FuelCharge> fuelCharges, PumpDisplay pumpDisplay, ArrayList<FuelType> fuelTypes) throws HeadlessException {
        this.fuelPumps = fuelPumps;
        this.pumpDisplay = pumpDisplay;
        this.customers = customers;
        this.fuelCharges = fuelCharges;
        this.fuelTypes = fuelTypes;
        initComponents();

        this.fuelPump.setModel(new DefaultComboBoxModel(fuelPumps.toArray()));
        this.fuelPumpRefill.setModel(new DefaultComboBoxModel(fuelPumps.toArray()));
        //this.fuelPump.addItem("Select Fuel Pump");
        //this.fuelPump.setSelectedIndex(this.getFuelPumps().size());
        this.fuelType.setModel(new DefaultComboBoxModel(fuelTypes.toArray()));

    }

    public PumpDisplay getPumpDisplay() {
        return pumpDisplay;
    }

    public void setPumpDisplay(PumpDisplay pumpDisplay) {
        this.pumpDisplay = pumpDisplay;
    }

    public ArrayList<Customer> getCustomers() {
        return customers;
    }

    public void setCustomers(ArrayList<Customer> customers) {
        this.customers = customers;
    }

    public ArrayList<FuelPump> getFuelPumps() {
        return fuelPumps;
    }

    public void setFuelPumps(ArrayList<FuelPump> fuelPumps) {
        this.fuelPumps = fuelPumps;
    }

    /**
     * Creates new form FuelDisplayForm
     */
    public FuelChargeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fuelPumpLbl = new javax.swing.JLabel();
        moneyAmtLbl = new javax.swing.JLabel();
        customerLbl = new javax.swing.JLabel();
        fuelAmtLbl = new javax.swing.JLabel();
        fuelPump = new javax.swing.JComboBox<>();
        amountMoney = new javax.swing.JTextField();
        customerInput = new javax.swing.JTextField();
        fuelAmount = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        customerName = new javax.swing.JLabel();
        customerSurname = new javax.swing.JLabel();
        discountTypeLbl = new javax.swing.JLabel();
        discountType = new javax.swing.JComboBox<>();
        resetBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fuelType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        currFuelPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        newFuelPrice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fuelPumpLbl1 = new javax.swing.JLabel();
        fuelPumpRefill = new javax.swing.JComboBox<>();
        fuelPumpLbl2 = new javax.swing.JLabel();
        refillAmount = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        availableAmount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fuelPumpLbl.setText("Fuel Pump");

        moneyAmtLbl.setText("Amount in Euro");

        customerLbl.setText("Customer ID");

        fuelAmtLbl.setText("Fuel Amount");

        fuelPump.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fuelPump.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fuelPumpItemStateChanged(evt);
            }
        });
        fuelPump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelPumpActionPerformed(evt);
            }
        });

        amountMoney.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                amountMoneyFocusLost(evt);
            }
        });

        customerInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerInputFocusLost(evt);
            }
        });
        customerInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerInputActionPerformed(evt);
            }
        });

        fuelAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fuelAmountFocusLost(evt);
            }
        });
        fuelAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelAmountActionPerformed(evt);
            }
        });

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        discountTypeLbl.setText("Discount Type");

        discountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTypeActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Prices List");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Fuel Charger Form");

        jLabel3.setText("Select Fuel Type");

        fuelType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fuelType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fuelTypeFocusGained(evt);
            }
        });
        fuelType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelTypeActionPerformed(evt);
            }
        });

        jLabel4.setText("Current Price");

        currFuelPrice.setEditable(false);

        jLabel5.setText("New Price");

        newFuelPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFuelPriceActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Refill");

        fuelPumpLbl1.setText("Amount to Refill");

        fuelPumpRefill.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fuelPumpRefill.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fuelPumpRefillItemStateChanged(evt);
            }
        });
        fuelPumpRefill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelPumpRefillActionPerformed(evt);
            }
        });

        fuelPumpLbl2.setText("Fuel Pump");

        refillAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refillAmountActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Available Amount");

        availableAmount.setEditable(false);
        availableAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableAmountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fuelPumpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fuelAmtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(resetBtn)
                                                .addGap(32, 32, 32)
                                                .addComponent(submitBtn))
                                            .addComponent(discountType, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(72, 72, 72)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(currFuelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(newFuelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fuelPumpLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addComponent(fuelPumpLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(88, 88, 88)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fuelPumpRefill, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(availableAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                                .addComponent(refillAmount, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(472, 472, 472)
                        .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(251, 251, 251)
                        .addComponent(customerSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moneyAmtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountTypeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amountMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fuelPump, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(855, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerName)
                    .addComponent(customerSurname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuelPumpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fuelPump, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(fuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(currFuelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fuelAmtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moneyAmtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(discountTypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(newFuelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(discountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fuelPumpRefill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fuelPumpLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(availableAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resetBtn)
                            .addComponent(submitBtn))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuelPumpLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(49, 49, 49))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel2)
                    .addContainerGap(540, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fuelPumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelPumpActionPerformed
        FuelPump fuelPump = (FuelPump) this.fuelPump.getSelectedItem();
        this.discountStrategies = new ArrayList<DiscountStrategy>();
        this.discountStrategies.add(new FreeFirstUnitsDiscount(BigDecimal.valueOf(5), 0, fuelPump.getFuelType().getFuelPrice()));
        this.discountStrategies.add(new FreeFirstUnitsDiscount(BigDecimal.ZERO, 5, fuelPump.getFuelType().getFuelPrice()));
        this.discountStrategies.add(new FixedAmtThresholdDiscount(BigDecimal.valueOf(15), BigDecimal.valueOf(5),
                0, 0, fuelPump.getFuelType().getFuelPrice()));
        this.discountType.setModel(new DefaultComboBoxModel(discountStrategies.toArray()));        // TODO add your handling code here:
    }//GEN-LAST:event_fuelPumpActionPerformed

    private void customerInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerInputActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:

        int customerId = 0;
        if (!this.customerInput.getText().equals("")) {
            customerId = Integer.valueOf(this.customerInput.getText());
        }

        Customer customer = Helper.getCustomerById(customers, customerId);

        FuelPump fuelPump = (FuelPump) this.fuelPump.getSelectedItem();

        FuelCharge fuelCharge;

        DiscountStrategy selectedDiscountStrategy;

        if (customer != null) {
            selectedDiscountStrategy = (DiscountStrategy) this.discountType.getSelectedItem();
        } else {
            selectedDiscountStrategy = null;
        }

        if (this.amountMoney.getText().equals("") && this.fuelAmount.getText().equals("")) {
            fuelCharge = new FuelCharge(fuelPump, 0, null, customer, selectedDiscountStrategy);
        } else if (this.amountMoney.getText().equals("")) {
            fuelCharge = new FuelCharge(fuelPump, Float.valueOf(this.fuelAmount.getText()), null, customer, selectedDiscountStrategy);
            if ((fuelPump.getTotalFuelAmt() - fuelCharge.getFuelAmount()) < 0) {
                JOptionPane.showMessageDialog(null, "There is no sufficient fuel left in the pump.");
                return;
            }
        } else if (this.fuelAmount.getText().equals("")) {
            fuelCharge = new FuelCharge(fuelPump, 0, new BigDecimal(this.amountMoney.getText()), customer, selectedDiscountStrategy);
            float normalizedFuelAmt = fuelCharge.getFuelAmount() + fuelCharge.getFuelDiscount();
            if ((fuelPump.getTotalFuelAmt() - normalizedFuelAmt) < 0) {
                JOptionPane.showMessageDialog(null, "There is no sufficient fuel left in the pump.");
                return;
            }
        } else {
            fuelCharge = new FuelCharge(fuelPump, Float.valueOf(this.fuelAmount.getText()), new BigDecimal(this.amountMoney.getText()), customer, selectedDiscountStrategy);
        }

        this.fuelPump.setEditable(false);
        this.customerInput.setEditable(false);
        this.amountMoney.setEditable(false);
        this.fuelAmount.setEditable(false);
        this.discountType.setEditable(false);

        fuelCharge.addObserver(this.pumpDisplay);
        fuelPump.addObserver(this.pumpDisplay);

        fuelCharges.add(fuelCharge);

        try {
            this.submitBtn.setEnabled(false);
            this.resetBtn.setEnabled(false);
            fuelCharge.chargeInProgress();

        } catch (InterruptedException ex) {
            Logger.getLogger(FuelChargeForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.submitBtn.setEnabled(true);
        this.resetBtn.setEnabled(false);
        this.fuelPump.setEditable(true);
        this.customerInput.setEditable(true);
        this.amountMoney.setEditable(true);
        this.fuelAmount.setEditable(true);
        this.discountType.setEditable(true);

    }//GEN-LAST:event_submitBtnActionPerformed

    private void fuelAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelAmountActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_fuelAmountActionPerformed

    private void fuelAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fuelAmountFocusLost
        // if Fuel Amount is not empty, then make amountMoney not editable
        if (!this.fuelAmount.getText().equals("")) {
            this.amountMoney.setEditable(false);
        } else {
            this.amountMoney.setEditable(true);
        }
    }//GEN-LAST:event_fuelAmountFocusLost

    private void amountMoneyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountMoneyFocusLost
        // if amountMoney is not empty, then make fuelAmount not editable
        if (!this.amountMoney.getText().equals("")) {
            this.fuelAmount.setEditable(false);
        } else {
            this.fuelAmount.setEditable(true);
        }
    }//GEN-LAST:event_amountMoneyFocusLost

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        this.customerInput.setText("");
        this.fuelAmount.setText("");
        this.amountMoney.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_resetBtnActionPerformed

    private void fuelPumpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fuelPumpItemStateChanged


    }//GEN-LAST:event_fuelPumpItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (Float.valueOf(this.newFuelPrice.getText()) > 0) {
            FuelType fuelType = Helper.getFuelTypeByFuel(fuelTypes, this.fuelType.getSelectedItem().toString());
            fuelType.setFuelPrice(new BigDecimal(this.newFuelPrice.getText()));
            JOptionPane.showMessageDialog(null, "Fuel Price changed successfully.");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void newFuelPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFuelPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newFuelPriceActionPerformed

    private void customerInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerInputFocusLost
        if (this.customerInput.getText() != "") {
            Customer customer = Helper.getCustomerById(customers, Integer.valueOf(this.customerInput.getText()));
            if (customer == null) {
                this.discountType.setVisible(false);
            } else {
                this.discountType.setVisible(true);
            }
        }

// TODO add your handling  here:
    }//GEN-LAST:event_customerInputFocusLost


    private void fuelTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fuelTypeFocusGained

    }//GEN-LAST:event_fuelTypeFocusGained

    private void fuelTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelTypeActionPerformed
        // TODO add your handling code here:
        FuelType fuelType = Helper.getFuelTypeByFuel(fuelTypes, this.fuelType.getSelectedItem().toString());
        this.currFuelPrice.setText(fuelType.getFuelPrice().toEngineeringString());
    }//GEN-LAST:event_fuelTypeActionPerformed

    private void discountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountTypeActionPerformed

    private void fuelPumpRefillItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fuelPumpRefillItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelPumpRefillItemStateChanged

    private void fuelPumpRefillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelPumpRefillActionPerformed
        FuelPump fuelPump = Helper.getFuelPumpByName(fuelPumps, this.fuelPumpRefill.getSelectedItem().toString());
        this.availableAmount.setText(Float.toString(fuelPump.getTotalFuelAmt()));        // TODO add your handling code here:
    }//GEN-LAST:event_fuelPumpRefillActionPerformed

    private void refillAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refillAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refillAmountActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (Validator.numberInputValidator(this.refillAmount.getText())) {
            FuelPump fuelPump = Helper.getFuelPumpByName(fuelPumps, this.fuelPumpRefill.getSelectedItem().toString());
            fuelPump.setTotalFuelAmt(fuelPump.getTotalFuelAmt() + Float.valueOf(this.refillAmount.getText()));
            JOptionPane.showMessageDialog(null, "Pump refuelled successfully.");
        } else {
            JOptionPane.showMessageDialog(null, "Please input a valid amount.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void availableAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableAmountActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FuelChargeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FuelChargeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FuelChargeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FuelChargeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FuelChargeForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountMoney;
    private javax.swing.JTextField availableAmount;
    private javax.swing.JTextField currFuelPrice;
    private javax.swing.JTextField customerInput;
    private javax.swing.JLabel customerLbl;
    private javax.swing.JLabel customerName;
    private javax.swing.JLabel customerSurname;
    private javax.swing.JComboBox<String> discountType;
    private javax.swing.JLabel discountTypeLbl;
    private javax.swing.JTextField fuelAmount;
    private javax.swing.JLabel fuelAmtLbl;
    private javax.swing.JComboBox<String> fuelPump;
    private javax.swing.JLabel fuelPumpLbl;
    private javax.swing.JLabel fuelPumpLbl1;
    private javax.swing.JLabel fuelPumpLbl2;
    private javax.swing.JComboBox<String> fuelPumpRefill;
    private javax.swing.JComboBox<String> fuelType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel moneyAmtLbl;
    private javax.swing.JTextField newFuelPrice;
    private javax.swing.JTextField refillAmount;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
